---
- hosts: localhost
  vars:
  - warName: webapp.war
  - warRemotePath: /opt/tomcat/webapp
  - warLocalPath: /var/lib/jenkins/workspace/maven_nexus/webapp/target

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}

  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/var/lib/jenkins/workspace/maven_nexus/webapp/target copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - Restart tomcat

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
  
  - name: wait for tomcat to start
    wait_for: port=8080 timeout=60

  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
